<a href="https://colab.research.google.com/github/Nhan2014/Nhan20146382/blob/main/ai_w8_24_3_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import Perceptron

In [ ]:
x=[[0,0],[1,0],[0,1],[1,1]]
y=[0,1,1,1]

In [ ]:
model=Perceptron()
model.fit(x,y)
model.score(x,y)

1.0

In [ ]:
x1=[[0.5,0],[0,0.5],[0.6, 0],[0.51,0],[0,0.51],[10,-2], [-0.2,1]]
y1=model.predict(x1)
print(y1)


[0 0 1 1 1 1 1]


In [ ]:
model.score(x1,y1)

1.0

In [ ]:
x2=[[-0.5,-0.5],[-0.5,0.5],[0.3, -0.5],[-0.1,1]]
y2=model.predict(x2)
print(y2)

[0 0 0 1]


In [ ]:
model.score(x2,y2)

1.0

In [ ]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [ ]:
iris=datasets.load_iris()
X=iris.data
Y=iris.target
print(X[:5])
print(Y[:5])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [ ]:
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.3)

In [ ]:
sc=StandardScaler()
sc.fit(X_train)
X_train_std=sc.transform(X_train)
X_test_std=sc.transform(X_test)

In [ ]:
model=Perceptron(max_iter=40,eta0=0.1,random_state=0)
model.fit(X_train, Y_train)
y_pred=model.predict(X_test)
print(Y_test)
print(y_pred)
print('Độ chính xác khi chưa scale:',accuracy_score(Y_test, y_pred))


[2 0 0 2 0 2 2 1 2 2 2 2 0 0 1 0 1 0 2 1 2 1 2 2 2 0 1 2 0 1 0 0 1 0 2 2 2
 0 2 1 0 2 0 0 1]
[2 0 0 2 0 2 2 1 2 2 2 2 0 0 2 0 0 0 2 1 2 1 2 2 2 0 1 2 0 1 0 0 1 0 2 2 2
 0 2 1 0 2 0 0 1]
Độ chính xác khi chưa scale: 0.9555555555555556


In [ ]:
model=Perceptron(max_iter=40,eta0=0.1,random_state=0)
model.fit(X_train_std, Y_train)
y_pred=model.predict(X_test_std)
print(Y_test)
print(y_pred)
print('Độ chính xác khi scale:',accuracy_score(Y_test, y_pred))


[2 0 0 2 0 2 2 1 2 2 2 2 0 0 1 0 1 0 2 1 2 1 2 2 2 0 1 2 0 1 0 0 1 0 2 2 2
 0 2 1 0 2 0 0 1]
[2 0 0 2 0 2 2 1 2 2 2 2 0 0 1 0 1 0 2 1 2 1 2 2 2 0 1 2 0 1 0 0 1 0 2 2 2
 0 1 1 0 2 0 0 1]
Độ chính xác khi scale: 0.9777777777777777


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving lung_cancer_examples.csv to lung_cancer_examples.csv


In [ ]:
import pandas as pd
df=pd.read_csv('lung_cancer_examples.csv')
df.head()

Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0    John         Wick   35       3      5       4       1
1    John  Constantine   27      20      2       5       1
2  Camela     Anderson   30       0      5       2       0
3    Alex       Telles   28       0      8       1       0
4   Diego     Maradona   68       4      5       6       1

In [ ]:
import numpy as np
X1=np.array(df.iloc[:,2:6])
Y1=np.array(df.iloc[:,6])
print(X1)
print(Y1)

[[35  3  5  4]
 [27 20  2  5]
 [30  0  5  2]
 [28  0  8  1]
 [68  4  5  6]
 [34  0 10  0]
 [58 15 10  0]
 [22 12  5  2]
 [45  2  6  0]
 [52 18  4  5]
 [33  4  8  0]
 [18 10  6  3]
 [25  2  5  1]
 [28 20  2  8]
 [34 25  4  8]
 [39 18  8  1]
 [42 22  3  5]
 [19 12  8  0]
 [62  5  4  3]
 [73 10  7  6]
 [55 15  1  3]
 [33  8  8  1]
 [22 20  6  2]
 [44  5  8  1]
 [77  3  2  6]
 [21 20  5  3]
 [37 15  6  2]
 [34 12  8  0]
 [55 20  1  4]
 [40 20  2  7]
 [36 13  5  2]
 [56 20  3  3]
 [47 15  1  8]
 [62 25  3  4]
 [26 10  7  2]
 [25 20  8  2]
 [59 20  3  4]
 [62 15  5  5]
 [33 25  8  2]
 [37 10  5  3]
 [50 20  2  4]
 [47 12  8  0]
 [69 20  5  4]
 [63 20  4  5]
 [39 15  7  2]
 [21 20  8  3]
 [31 20  9  4]
 [28 10  4  1]
 [53 20  6  3]
 [62 20  5  6]
 [42 12  6  2]
 [44 30  1  6]
 [26 34  1  8]
 [35 20  5  1]
 [26 13  6  1]
 [77 20  5  4]
 [75 15  3  5]
 [43 30  3  8]
 [51 25  9  0]]
[1 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 1 0 1 1 1 0 0 0 1 0 0 0 1 1 0 1 1 1 0 0 1
 1 0 0 1 0 1 1 0 0 0 0 1 1 0 1 1 0 0 1 

In [ ]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
X1_train, X1_test, Y1_train, Y1_test=train_test_split(X1,Y1,test_size=0.3)

In [ ]:
sc=StandardScaler()
sc.fit(X1_train)
X1_train_std=sc.transform(X1_train)
X1_test_std=sc.transform(X1_test)

In [ ]:
model1=Perceptron(max_iter=40,eta0=0.1,random_state=0)
model1.fit(X1_train, Y1_train)
y1_pred=model1.predict(X1_test)
print(Y1_test)
print(y1_pred)
print('Độ chính xác khi chưa scale:',accuracy_score(Y1_test, y1_pred))

[1 1 1 1 0 1 0 1 0 1 0 1 0 0 0 1 0 0]
[1 1 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0]
Độ chính xác khi chưa scale: 0.8333333333333334


In [ ]:
model1=Perceptron(max_iter=40,eta0=0.1,random_state=0)
model1.fit(X1_train_std, Y1_train)
y1_pred=model1.predict(X1_test_std)
print(Y1_test)
print(y1_pred)
print('Độ chính xác khi scale:',accuracy_score(Y1_test, y1_pred))

[1 1 1 1 0 1 0 1 0 1 0 1 0 0 0 1 0 0]
[1 1 1 0 0 1 0 1 0 1 0 1 0 0 0 1 0 0]
Độ chính xác khi scale: 0.9444444444444444


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving pima-indians-diabetes.csv to pima-indians-diabetes.csv


In [ ]:
import pandas as pd
df=pd.read_csv('pima-indians-diabetes.csv')
df.head()

6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

In [ ]:
import numpy as np
X2=np.array(df.iloc[:,:7])
Y2=np.array(df.iloc[:,8])
print(X2)
print(Y1)

[[1.00e+00 8.50e+01 6.60e+01 ... 0.00e+00 2.66e+01 3.51e-01]
 [8.00e+00 1.83e+02 6.40e+01 ... 0.00e+00 2.33e+01 6.72e-01]
 [1.00e+00 8.90e+01 6.60e+01 ... 9.40e+01 2.81e+01 1.67e-01]
 ...
 [5.00e+00 1.21e+02 7.20e+01 ... 1.12e+02 2.62e+01 2.45e-01]
 [1.00e+00 1.26e+02 6.00e+01 ... 0.00e+00 3.01e+01 3.49e-01]
 [1.00e+00 9.30e+01 7.00e+01 ... 0.00e+00 3.04e+01 3.15e-01]]
[0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0 1
 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0 0
 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1
 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1
 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1 0
 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1
 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0 1
 0 1 0 1 1 0 1 0 0 1 0 1 1 0

In [ ]:
X2_train, X2_test, Y2_train, Y2_test=train_test_split(X2,Y2,test_size=0.3)

In [ ]:
sc=StandardScaler()
sc.fit(X2_train)
X2_train_std=sc.transform(X2_train)
X2_test_std=sc.transform(X2_test)

In [ ]:
model2=Perceptron(max_iter=40,eta0=0.1,random_state=0)
model2.fit(X2_train, Y2_train)
y2_pred=model2.predict(X2_test)
print(Y2_test)
print(y2_pred)
print('Độ chính xác khi chưa scale:',accuracy_score(Y2_test, y2_pred))

[0 1 1 0 0 0 0 1 1 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 1 1 0 1 0 1 0 0 1 0 1 0
 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0
 0 1 0 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 1 1 0 0 1 0 0 1 1 1 1 1 1 1 0 0 1 0
 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 1 0 0 1 0 1 0 1 1 0 1 0 1 0 0 1
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 0 0 1 0 1 1 0 1 0 0
 1 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 1 1 1 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 1
 0 1 0 0 0 1 0 0 1]
[0 1 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0
 0 1 1 1 0 0 1 0 1 1 1 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 0 1
 0 0 0 0 0 1 1 0 0 1 0 1 1 1 0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 0 1
 0 1 1 1 0 0 0 0 0 1 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0
 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1
 1 0 1 1 0 0 1 1 0 1 1 0 0 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 1
 0 0 0 1 0 0 0 0 1]
Độ chính xác khi chưa scale: 0.6753246753246753


In [ ]:
model2=Perceptron(max_iter=40,eta0=0.1,random_state=0)
model2.fit(X2_train_std, Y2_train)
y2_pred=model2.predict(X2_test_std)
print(Y2_test)
print(y2_pred)
print('Độ chính xác khi scale:',accuracy_score(Y2_test, y2_pred))

[0 1 1 0 0 0 0 1 1 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 1 1 0 1 0 1 0 0 1 0 1 0
 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0
 0 1 0 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 1 1 0 0 1 0 0 1 1 1 1 1 1 1 0 0 1 0
 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 1 0 0 1 0 1 0 1 1 0 1 0 1 0 0 1
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 0 0 1 0 1 1 0 1 0 0
 1 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 1 1 1 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 1
 0 1 0 0 0 1 0 0 1]
[0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0 1 1 0 0 0
 0 0 1 1 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 1 0 0
 0 0 1 0 0 1 0 0 0 1 0 1 1 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 1
 0 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1
 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1 1 0 1 0 0 1 1 0
 1 1 0 1 0 0 1 1 0 1 1 0 0 1 0 0 0 1 1 1 0 0 1 1 1 1 0 1 0 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 1]
Độ chính xác khi scale: 0.7532467532467533
